# Generated by Django 3.2.3 on 2021-05-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210530_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_type',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_variant_1',
            field=models.CharField(default='answer example', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_variant_2',
            field=models.CharField(default='answer example', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_variant_3',
            field=models.CharField(default='answer example', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_variant_4',
            field=models.CharField(default='answer example', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='expected_answer_type',
            field=models.CharField(choices=[('R', 'one answer'), ('M', 'few answers'), ('T', 'user input')], default=None, max_length=8),
            preserve_default=False,
        ),
    ]
