# Generated by Django 3.2.3 on 2021-05-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210530_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='expected_answer_type',
            field=models.CharField(choices=[('regular', 'one answer'), ('multiple', 'few answers'), ('text', 'user input')], max_length=8),
        ),
    ]
